<?php
require "lessphp/lessc.inc.php";
$less = new lessc;
$less->checkedCompile("less/control.less", "css/control.css"); ?>
<html>
    <head>
        <title>Wendy | Панель управління</title>
        <meta charset='utf-8' http-equiv="content-type">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="../css/control.css"/>
    </head>
<body>
<div class="container">
<?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
    <ul class="nav nav-tabs">
        <li><a href="/admin"><span class="glyphicon glyphicon-home"></span></a></li>
        <li><a href="/admin/main">Головна</a></li>
        <li><a href="/admin/lovestory">Lovestory</a></li>
        <li><a href="/admin/guest">Для гостей</a></li>
        <li><a href="/admin/gallery">Галерея</a></li>
        <li><a href="/admin/wish">Побажання</a></li>
        <li><a href="/admin/contact">Контакти</a></li>
        <li style="float: right"><a href="/auth/logout">Выход</a></li>
        <li style="float: right"><a href="/admin/help">Допомога</a></li>
    </ul>
<?php } ?>
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>