<html>
    <head>
        <title>index</title>
        <meta charset='utf-8' http-equiv="content-type">
    </head>
<body>
<ul>
    <li><a href="/control/main">головна</a></li>
    <li><a href="/control/lovestory">lovestory</a></li>
    <li><a href="/control/guest">для гостей</a></li>
    <li><a href="/control/gallery">gallery</a></li>
    <li><a href="/control/wish">побажання</a></li>
    <li><a href="/control/contact">контакти</a></li>
</ul>
    <?php echo $this->layout()->content; ?>
</body>
</html>