<?php $user = Zend_Auth::getInstance()->getIdentity();
$data = $this->data;
?>
<table>
    <thead>
    <tr>
        <th>Адреса сайту</th>
        <th>Статус</th>
        <th>Дата реєстрації</th>
        <th>Дата закінчення</th>
        <th>E-mail</th>
    </tr>
    </thead>
    <tr>
        <td><a href="<?php echo "http://".$_SERVER['SERVER_NAME']."/".$user->sitename; ?>" target="_blank"><?php echo $_SERVER['SERVER_NAME']."/".$user->sitename; ?></a></td>
        <td><?php if($data['publish'] == 0) { ?>
                <span style="color: #ff0000">Неактивний</span>
            <?php } else { ?>
                Працює
            <?php } ?>
        </td>
        <td><?php echo date("d-m-Y", $user->date); ?></td>
        <td><?php echo date("d-m-Y", $user->date+31556926); ?></td>
        <td><?php echo $user->email; ?></td>
    </tr>
</table>
<p class="alert alert-danger">Щоб активувати сайт потрібно оплатити згідно рахунку. Після чого протягом 24 год. ваш сайт запрацює. тут можна продублювати реквізити</p>